config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'books/new'=> 'books#new'
  post 'books' => 'books#create'
  get 'books' =>'books#index'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, {presence: true}
  validates :body, {presence: true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
     @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    redirect_to book_path(@book.id)
    else
    render :edit
    end
    flash[:notice] = "Book was successfully updated."
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

   def create
    @book = Book.new(book_params)
    if @book.save
    redirect_to book_path(@book.id)
    else
    @books = Book.all
    render :index
    end
    flash[:notice] = "Book was successfully created."
   end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>

<% if @book.errors.any? %>
 <h3><%= @book.errors.count %>errors prohibited this book from being saved:</h3>
 <ul>
   <% @book.errors.full_messages.each do |messages| %>
   <li><%= messages %></li>
   <% end %>
 </ul>
<% end %>

  <h4>本のタイトル</h4>
  <%= f.text_field :title %>
  <h4>感想</h4>
  <%= f.text_area :body %>
 <br> <%= f.submit 'Update Book' %></br>

  <% end %>

  <%= link_to "Show", book_path(@book.id) %>
  |
  <%= link_to "Back", books_path %>

app/views/books/index.html.erb
<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>本のタイトル</th>
      <th>感想</th>
    </tr>
  </thead>

<tbody>
<% @books.each do |book| %>
<tr>
<td><%= book.title %></td>
<td><%= book.body %></td>
<td><%= link_to "Show", book_path(book.id) %></td>
<td><%= link_to "Edit", edit_book_path(book.id) %></td>
<td><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure？" %></td>
</tr>
</tbody>

<% end %>

</table>



<h2>New Book</h2>
<!-- form_with部分 -->
<%= form_with model: @book, url:'/books', local:true do |f| %>

<% if @book.errors.any? %>
 <h3><%= @book.errors.count %>errors prohibited this book from being saved:</h3>
 <ul>
   <% @book.errors.full_messages.each do |messages| %>
   <li><%= messages %></li>
   <% end %>
 </ul>
<% end %>

  <h4>本のタイトル</h4>
  <%= f.text_field :title %>
  <h4>感想</h4>
  <%= f.text_area :body %>
 <br><%= f.submit 'Create Book' %></br>
  <% end %>

app/views/books/new.html.erb
<h2>New Book</h2>
<!-- form_with部分 -->
<%= form_with model: @book, url:'/books', local:true do |f| %>
  <h4>本のタイトル</h4>
  <%= f.text_field :title %>
  <h4>感想</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
 <% if flash[:notice] %>
     <p id="notice">
       <%= flash[:notice] %>
     </p>
   <% end %>

<p>
<strong>本のタイトル：</strong>
<%= @book.title %>
</p>
<p>
<strong>感想：</strong>
<%= @book.body %>
</p>

<%= link_to "Edit", edit_book_path(@book.id) %>
|
<%= link_to "Back", books_path %>

app/views/homes/top.html.erb
<h1>ようこそ<strong>Bookers</strong>へ！</h1>

<p><strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や</p>

<p>印象を共有し交換することができます</p>

 <%= link_to "Start", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>